//
//  GTFoundation.h
//  Pods
//
//  Created by liuxc on 2018/11/16.
//

#if __has_include(<GTCategories/GTFoundation.h>)
#import <GTCategories/NSArray+GTBlock.h>
#import <GTCategories/NSArray+GTSafeAccess.h>
#import <GTCategories/NSBundle+GTAppIcon.h
#import <GTCategories/NSData+GTAPNSToken.h>
#import <GTCategories/NSData+GTBase64.h>
#import <GTCategories/NSData+GTDataCache.h>
#import <GTCategories/NSData+GTEncrypt.h>
#import <GTCategories/NSData+GTGzip.h>
#import <GTCategories/NSData+GTHash.h>
#import <GTCategories/NSData+GTzlib.h>
#import <GTCategories/NSData+GTPCM.h>
#import <GTCategories/NSDate+GTAddition.h>
#import <GTCategories/NSDate+GTCupertinoYankee.h>
#import <GTCategories/NSDate+GTExtension.h>
#import <GTCategories/NSDate+GTFormatter.h>
#import <GTCategories/NSDate+GTInternetDateTime.h>
#import <GTCategories/NSDate+GTLunarCalendar.h>
#import <GTCategories/NSDate+GTReporting.h>
#import <GTCategories/NSDate+GTZeroDate.h>
#import <GTCategories/NSDateFormatter+GTMake.h>
#import <GTCategories/NSDictionary+GTBlock.h>
#import <GTCategories/NSDictionary+GTJSONString.h>
#import <GTCategories/NSDictionary+GTMerge.h>
#import <GTCategories/NSDictionary+GTSafeAccess.h>
#import <GTCategories/NSDictionary+GTURL.h>
#import <GTCategories/NSDictionary+GTXML.h>
#import <GTCategories/NSException+GTTrace.h>
#import <GTCategories/NSFileManager+GTPaths.h>
#import <GTCategories/NSIndexPath+GTOffset.h>
#import <GTCategories/NSInvocation+GTBlocks.h>
#import <GTCategories/NSNotificationCenter+GTMainThread.h>
#import <GTCategories/NSDecimalNumber+GTCalculatingByString.h>
#import <GTCategories/NSDecimalNumber+GTExtensions.h>
#import <GTCategories/NSNumber+GTCGFloat.h>
#import <GTCategories/NSNumber+GTRomanNumerals.h>
#import <GTCategories/NSNumber+GTRound.h>
#import <GTCategories/NSObject+GTAddProperty.h>
#import <GTCategories/NSObject+GTAlert.h>
#import <GTCategories/NSObject+GTAppInfo.h>
#import <GTCategories/NSObject+GTAssociatedObject.h>
#import <GTCategories/NSObject+GTAutoCoding.h>
#import <GTCategories/NSObject+GTBlocks.h>
#import <GTCategories/NSObject+GTBlockTimer.h>
#import <GTCategories/NSObject+GTBundle.h>
#import <GTCategories/NSObject+GTEasyCopy.h>
#import <GTCategories/NSObject+GTGCD.h>
#import <GTCategories/NSObject+GTIP.h>
#import <GTCategories/NSObject+GTKVOBlocks.h>
#import <GTCategories/NSObject+GTNavigation.h>
#import <GTCategories/NSObject+GTReflection.h>
#import <GTCategories/NSObject+GTRuntime.h>
#import <GTCategories/NSRunLoop+GTPerformBlock.h>
#import <GTCategories/NSSet+GTBlocks.h>
#import <GTCategories/NSString+GTBase64.h>
#import <GTCategories/NSString+GTContains.h>
#import <GTCategories/NSString+GTDictionaryValue.h>
#import <GTCategories/NSString+GTEmoji.h>
#import <GTCategories/NSString+GTEncrypt.h>
#import <GTCategories/NSString+GTHash.h>
#import <GTCategories/NSString+GTHTML.h>
#import <GTCategories/NSString+GTMatcher.h>
#import <GTCategories/NSString+GTMIME.h>
#import <GTCategories/NSString+GTNormalRegex.h>
#import <GTCategories/NSString+GTPinyin.h>
#import <GTCategories/NSString+GTRemoveEmoji.h>
#import <GTCategories/NSString+GTScore.h>
#import <GTCategories/NSString+GTSize.h>
#import <GTCategories/NSString+GTStringPages.h>
#import <GTCategories/NSString+GTTrims.h>
#import <GTCategories/NSString+GTURLEncode.h>
#import <GTCategories/NSString+GTUUID.h>
#import <GTCategories/NSString+GTXMLDictionary.h>
#import <GTCategories/NSTimer+GTAddition.h>
#import <GTCategories/NSTimer+GTBlocks.h>
#import <GTCategories/NSURL+GTParam.h>
#import <GTCategories/NSURL+GTURLQuery.h>
#import <GTCategories/NSUserDefaults+GTiCloudSync.h>
#import <GTCategories/NSUserDefaults+GTSafeAccess.h>
#else
#import "NSArray+GTBlock.h"
#import "NSArray+GTSafeAccess.h"
#import "NSBundle+GTAppIcon.h"
#import "NSData+GTAPNSToken.h"
#import "NSData+GTBase64.h"
#import "NSData+GTDataCache.h"
#import "NSData+GTEncrypt.h"
#import "NSData+GTGzip.h"
#import "NSData+GTHash.h"
#import "NSData+GTzlib.h"
#import "NSData+GTPCM.h"
#import "NSDate+GTAddition.h"
#import "NSDate+GTCupertinoYankee.h"
#import "NSDate+GTExtension.h"
#import "NSDate+GTFormatter.h"
#import "NSDate+GTInternetDateTime.h"
#import "NSDate+GTLunarCalendar.h"
#import "NSDate+GTReporting.h"
#import "NSDate+GTZeroDate.h"
#import "NSDateFormatter+GTMake.h"
#import "NSDictionary+GTBlock.h"
#import "NSDictionary+GTJSONString.h"
#import "NSDictionary+GTMerge.h"
#import "NSDictionary+GTSafeAccess.h"
#import "NSDictionary+GTURL.h"
#import "NSDictionary+GTXML.h"
#import "NSException+GTTrace.h"
#import "NSFileManager+GTPaths.h"
#import "NSIndexPath+GTOffset.h"
#import "NSInvocation+GTBlocks.h"
#import "NSNotificationCenter+GTMainThread.h"
#import "NSDecimalNumber+GTAddition.h"
#import "NSDecimalNumber+GTCalculatingByString.h"
#import "NSNumber+GTCGFloat.h"
#import "NSNumber+GTRomanNumerals.h"
#import "NSNumber+GTRound.h"
#import "NSObject+GTAddProperty.h"
#import "NSObject+GTAlert.h"
#import "NSObject+GTAppInfo.h"
#import "NSObject+GTAssociatedObject.h"
#import "NSObject+GTAutoCoding.h"
#import "NSObject+GTBlocks.h"
#import "NSObject+GTBlockTimer.h"
#import "NSObject+GTBundle.h"
#import "NSObject+GTEasyCopy.h"
#import "NSObject+GTGCD.h"
#import "NSObject+GTIP.h"
#import "NSObject+GTKVOBlocks.h"
#import "NSObject+GTNavigation.h"
#import "NSObject+GTReflection.h"
#import "NSObject+GTRuntime.h"
#import "NSRunLoop+GTPerformBlock.h"
#import "NSSet+GTBlocks.h"
#import "NSString+GTBase64.h"
#import "NSString+GTContains.h"
#import "NSString+GTDictionaryValue.h"
#import "NSString+GTEmoji.h"
#import "NSString+GTEncrypt.h"
#import "NSString+GTHash.h"
#import "NSString+GTHTML.h"
#import "NSString+GTMatcher.h"
#import "NSString+GTMIME.h"
#import "NSString+GTNormalRegex.h"
#import "NSString+GTPinyin.h"
#import "NSString+GTRemoveEmoji.h"
#import "NSString+GTScore.h"
#import "NSString+GTSize.h"
#import "NSString+GTStringPages.h"
#import "NSString+GTTrims.h"
#import "NSString+GTURLEncode.h"
#import "NSString+GTUUID.h"
#import "NSString+GTXMLDictionary.h"
#import "NSTimer+GTAddition.h"
#import "NSTimer+GTBlocks.h"
#import "NSURL+GTParam.h"
#import "NSURL+GTURLQuery.h"
#import "NSUserDefaults+GTiCloudSync.h"
#import "NSUserDefaults+GTSafeAccess.h"

#endif
